parameters:
    matchmaker.weights:
        pet_type: 25
        activity_home: 20
        experience: 15
        age_preference: 15

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $matchmakerConfig:
                weights: "%matchmaker.weights%"

    App\:
        resource: "../src/"
